



@Component
export default struct  InformationList {
  build() {
    Column() {
      Text('个人信息编辑')
      List(){
        ListItem(){
          Text('hello  world')
        }
        .width('100%')
        .height('20%')

        ListItem(){
          Text('hello  world')

        }
        .width('100%')
        .height('20%')
        ListItem(){
          Text('hello  world')

        }
        .width('100%')
        .height('20%')
        ListItem(){
          Text('hello  world')

        }
        .width('100%')
        .height('20%')
        ListItem(){
          Text('hello  world')

        }
        .width('100%')
        .height('20%')
      }
      .height('50%')
    }

  }
}