/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Achievement map info
 */
export default class AchievementMapInfo {
  //补充微笑勋章
  smile_off_1: Resource = $r('app.media.ic_badge_smile_1_off');
  smile_on_1: Resource = $r('app.media.ic_badge_smile_1_on');
  smile_off_2: Resource = $r('app.media.ic_badge_smile_2_off');
  smile_on_2: Resource = $r('app.media.ic_badge_smile_2_on');
  smile_off_3: Resource = $r('app.media.ic_badge_smile_3_off');
  smile_on_3: Resource = $r('app.media.ic_badge_smile_3_on');
  // smile_off_4: Resource = $r('app.media.ic_badge_smile_4_off');
  // smile_on_4: Resource = $r('app.media.ic_badge_smile_4_on');

  off_3: Resource = $r('app.media.ic_badge_3_off');
  on_3: Resource = $r('app.media.ic_badge_3_on');
  off_7: Resource = $r('app.media.ic_badge_7_off');
  on_7: Resource = $r('app.media.ic_badge_7_on');
  off_30: Resource = $r('app.media.ic_badge_30_off');
  on_30: Resource = $r('app.media.ic_badge_30_on');
  off_50: Resource = $r('app.media.ic_badge_50_off');
  on_50: Resource = $r('app.media.ic_badge_50_on');
  off_73: Resource = $r('app.media.ic_badge_73_off');
  on_73: Resource = $r('app.media.ic_badge_73_on');
  off_99: Resource = $r('app.media.ic_badge_99_off');
  on_99: Resource = $r('app.media.ic_badge_99_on');
}
